### ISSUE TITLE
OAuth Error in both Gmail and Fb

### ISSUE THREAD

**Issue by sachincool** [thakursaurabh1998/linux-server-config#2]
OAuth no longer Working
Please FIx it Asap!!

**Comment by thakursaurabh1998** [comment]
OAuth can only work if I buy my domain name and register it with Facebook and google because of their restrictions of production app. It can't work with the ip address I am using to access the website. But if you want to play around with the website and check it out. I can give you tester access from Facebook OAuth. Let me know.
